apiVersion: v1
kind: Service
metadata:
  name: nexus-local
  namespace: nexus-local
spec:
  type: NodePort
  selector:
    app: nexus-local
  ports:
    - name: webhook
      port: 9876
      targetPort: 9876
      nodePort: 30877
      protocol: TCP
